---
- name: Converge
  hosts: all
  tasks:
    - include_role:
        name: docker_service_configs
      vars:
        service_name: foo
        service_configs:
          - prefix: bar
            content: Hello world
            filename: /foo.conf

    - debug:
        msg: "{{ docker_service_configs }}"
